create table division (
    id integer generated by default as identity,
    capital varchar(255),
    name varchar(255),
    region varchar(255),
    primary key (id)
);

create table district (
    division_id integer not null,
    id integer generated by default as identity,
    name varchar(255) not null,
    primary key (id),
    constraint fk_dictrict_to_division foreign key (division_id) references division
);
