import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UsersProvider } from "@/providers/users-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <nav className="px-8 py-4 bg-indigo-600 text-white flex justify-between">
          <span>Using State</span>

          <ul className="flex">
            <li className="px-2">
              <Link href={'/simple'}>Simple State</Link>
            </li>
            <li className="px-2">
              <Link href={'/input'}>Simple Input</Link>
            </li>
            <li className="px-2">
              <Link href={'/users'}>User List</Link>
            </li>
          </ul>
        </nav>

        <main className="px-8 py-4">
          <UsersProvider>
            {children}
          </UsersProvider>
        </main>
      </body>
    </html>
  );
}
