create table division (
    id integer generated by default as identity,
    capital varchar(255),
    name varchar(255),
    region varchar(255),
    primary key (id)
);

insert into division (name, capital, region) values (',Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values (',Bago Region', 'Bago', 'South, Central');
insert into division (name, capital, region) values (',Chin State', 'Hakha', 'North, West');
insert into division (name, capital, region) values (',Kachin State', 'Myitkyina', 'North');
insert into division (name, capital, region) values (',Kayah State', 'Loikaw', 'East');
insert into division (name, capital, region) values (',Kayin State', 'Hpa-an', 'South, East');
insert into division (name, capital, region) values (',Magway Region', 'Magwe', 'Central');
insert into division (name, capital, region) values (',Mandalay Region', 'Mandalay', 'Central');
insert into division (name, capital, region) values (',Mon State', 'Mawlamyine', 'South');
insert into division (name, capital, region) values (',Naypyidaw Union Territory', 'Naypyidaw', 'Central');
insert into division (name, capital, region) values (',Rakhine State', 'Sittwe', 'West');
insert into division (name, capital, region) values (',Sagaing Region', 'Monywa', 'North, West');
insert into division (name, capital, region) values (',Shan State', 'Taunggyi', 'North, East');
insert into division (name, capital, region) values (',Tanintharyi Region', 'Dawei', 'South');
insert into division (name, capital, region) values (',Yangon Region', 'Yangon', 'Central');